### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nmweizi** [aboutmydreams/pycapt#4]
![image](https://user-images.githubusercontent.com/1232444/63207898-852d2580-c100-11e9-9b4a-55654512fd6a.png)

```python
img = Image.open('3LLW.png')
img1 = pycapt.two_value(img,Threshold=100)
img1.show()
img_list = pycapt.cut_img_to_img_list(img1,max_width=60,background=255)
```

Traceback (most recent call last):
  File "extract_single_letters_from_captchas.py", line 29, in <module>
    img_list = pycapt.cut_img_to_img_list(img1, max_width=30, background=255)
  File "d:\python36\lib\site-packages\pycapt\__init__.py", line 74, in cut_img_to_img_list
    return pycapt.solve_it.cut_img_to_img_list(image,max_width,background=255)
  File "d:\python36\lib\site-packages\pycapt\solve_it\__init__.py", line 55, in cut_img_to_img_list
    mode_list = pycapt.solve_it.cut_img.cut_img(image,max_width)
  File "d:\python36\lib\site-packages\pycapt\solve_it\cut_img.py", line 139, in cut_img
    li = cut_mode(my_mode,max_width=30)
  File "d:\python36\lib\site-packages\pycapt\solve_it\cut_img.py", line 66, in cut_mode
    alpha_list = list(range(i,bian_yuan[(k+1)*2-1]+1))
IndexError: list index out of range

**Comment by aboutmydreams** [comment]
max_width is too big ?

**Comment by nmweizi** [comment]
max_width=20，It's still the same
